apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: flink
    system.processing: "true"
data:
  base-config: |+
{{ .Values.base_config | indent 4 }}

  flink-conf: |+
{{ .Values.flink_conf | indent 4 }}

  {{ .Release.Name }}: |+
{{ .Values.job_config | indent 4}}  

  log4j_console_properties: |+
{{ .Values.log4j_console_properties | indent 4 }}

